### ISSUE TITLE
error with multi_gpus inference

### ISSUE THREAD

**Issue by GordonDongZHAO** [THUDM/CogVLM2#10]
### System Info / 系統信息

hi, I have 4 3090 GPUs.

device_map = infer_auto_device_map(
    model=model,
    max_memory={i: "12GiB" for i in range(torch.cuda.device_count())},
    # set 23GiB for each GPU, depends on your GPU memory, you can adjust this value
    no_split_module_classes=["CogVLMDecoderLayer"]
)

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

File "/root/.cache/huggingface/modules/transformers_modules/THUDM/cogvlm2-llama3-chinese-chat-19B/8a603a29c162ac4e3e3fa710b3f18fde056e97d0/visual.py", line 83, in forward
    output = mlp_input + mlp_output
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:2 and cuda:3!

### Expected behavior / 期待表现

How to solve this problem？

**Comment by peytoncai** [comment]
same

**Comment by AlchemistD** [comment]
A100 40g 多卡 inference 报这个 error，很奇怪

File /disk/cache/modules/transformers_modules/util.py:430, in FastRotaryEmbedding._update_cos_sin_cache(self, seqlen, position_id, device, dtype)
    428         inv_freq = self.inv_freq
    429 else:
--> 430     t = torch.arange(seqlen, device=device, dtype=self.inv_freq.dtype)
    431     inv_freq = self.inv_freq
    432 freqs = torch.einsum("i,j->ij", t, inv_freq)

RuntimeError: Storage size calculation overflowed with sizes=[4872363901336820736]

**Comment by zRzRzRzRzRzRzR** [comment]
用我们multi gpu载入的方法，应该能解决问题

**Comment by Cherryjingyao** [comment]
hidden_states = layer_module(hidden_states)
  File "/data/anaconda3/envs/RoboFlamingo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/pfs-data/huggingface/modules/transformers_modules/visual.py", line 118, in forward
    output = mlp_input + mlp_output
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cuda:1!
我用了两张卡推理，也遇到同样的问题
