### ISSUE TITLE
这个模型好厉害，在Int4精度下都能做到准确无误，只能说是最强OCR神器，期待第二版

### ISSUE THREAD

**Issue by whysirier** [THUDM/CogVLM2#103]
### System Info / 系統信息

后续会有更新不

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1张V100就能跑

### Expected behavior / 期待表现

期待后续更新

**Comment by zRzRzRzRzRzRzR** [comment]
感谢鼓励和支持！

**Comment by chuangzhidan** [comment]
> ### System Info / 系統信息
> 后续会有更新不
> 
> ### Who can help? / 谁可以帮助到您？
> _No response_
> 
> ### Information / 问题信息
> * [ ]  The official example scripts / 官方的示例脚本
> * [ ]  My own modified scripts / 我自己修改的脚本和任务
> 
> ### Reproduction / 复现过程
> 1张V100就能跑
> 
> ### Expected behavior / 期待表现
> 期待后续更新

你测试图片是怎样的，有难度吗
