### ISSUE TITLE
这个模型有没有好的推理加速方法？推理耗时太久了

### ISSUE THREAD

**Issue by starlxx** [THUDM/CogVLM2#104]
### System Info / 系統信息

A100

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

在使用这个模型推理过程中，发现推理单张图片耗时大概在10s左右，时间太久了，有没有好的推理加速方法呢？

### Expected behavior / 期待表现

推理加速

**Comment by ty520** [comment]
我的也一样，A100，平均4-5s一张图片

**Comment by MultiChen** [comment]
+1，亟需推理加速支持

**Comment by 1049451037** [comment]
我们发布了基于TGI的cogvlm推理：https://huggingface.co/THUDM/cogvlm2-llama3-chat-19B-tgi

可以参照readme的news：

🔥🔥 News: 2024/6/8:We release [CogVLM2 TGI Weight](https://huggingface.co/THUDM/cogvlm2-llama3-chat-19B-tgi), which is a model can be inferred in [TGI](https://huggingface.co/docs/text-generation-inference/en/index). See Inference Code in [here](https://github.com/leizhao1234/cogvlm2)

**Comment by ericzhou571** [comment]
使用tgi部署的遇到报错
ValueError: Unsupported model type cogvlm2
使用的镜像为：ghcr.io/huggingface/text-generation-inference:2.1.0

**Comment by xzhou42** [comment]
是的
ValueError: Unsupported model type cogvlm2
