### ISSUE TITLE
这个问题是否可以忽略？ 还是需要将tokenizer.padding_side = 'left'

### ISSUE THREAD

**Issue by Guodashen222** [THUDM/CogVLM2#11]
![11b7b3b637e2d1272e5b8fc68759065](https://github.com/THUDM/CogVLM2/assets/93236115/8a39cdba-2370-4021-9fd1-af99c85f8276)

**Comment by zRzRzRzRzRzRzR** [comment]
可以

**Comment by Guodashen222** [comment]
#
