### ISSUE TITLE
[Question] 请问如果是同一张图片对应多个qa对的数据，应该怎么组织成训练数据？

### ISSUE THREAD

**Issue by XuRui314** [THUDM/CogVLM2#110]
正常的格式应该是下面这样：
.llava_details-minigpt4_3500_formate
├── images
│   └── 00000001.jpg
└── labels
    └── 00000001.json

{
  "conversations": [
    {
      "role": "user",
      "content": "What can be inferred about the zebras' behavior and surroundings?"
    },
    {
      "role": "assistant",
      "content": "Based on the image...."
    }
  ]
}

所以一个简单的思路就是把同一张图片复制后分别命名，有没有更好的解决方法

**Comment by zRzRzRzRzRzRzR** [comment]
上述思路是最简单的，也是适合目前这个demo的数据读入的。
如果你想实现这个需求并用你认为更高效的数据存储方法也是可以的，关键点在于修改
class ConversationDataset(Dataset):的部分
修改成能读入你的数据集的格式并对齐
