### ISSUE TITLE
How many GPU memory is required to inference CogVLM2 in float16

### ISSUE THREAD

**Issue by Luciennnnnnn** [THUDM/CogVLM2#114]
### Feature request  / 功能建议

How many GPU memory is required to inference CogVLM2 in float16

### Motivation / 动机

no

### Your contribution / 您的贡献

no

**Comment by liuky74** [comment]
16GB*3

**Comment by Luciennnnnnn** [comment]
> 16GB*3

where *3 comes from?

**Comment by liuky74** [comment]
> > 16GB*3
> 
> where *3 comes from?

I deployed the FP16 model on my 3*3090 server, nvidia-smi like:
![image](https://github.com/THUDM/CogVLM2/assets/29391214/a2c25b4f-94a0-4b93-98fb-d1764dfec659)

**Comment by KSimulation** [comment]
Would a single A100 with 40G vram be ok?

**Comment by zRzRzRzRzRzRzR** [comment]
work，but only few conversation and it will overflow ， more than 40G
