### ISSUE TITLE
openai_api_demo.py on 2 nvidia 3090 GPU

### ISSUE THREAD

**Issue by arit2** [THUDM/CogVLM2#116]
Hi Great project. I'm trying to run openai_api_demo.py on 2 nvidia 3090 graphics cards. Unfortunately, the current script works great but on 1 card with --quant 4
I would like to be able to use the 2 GPU model with full precision.
Thank you in advance for your help

**Comment by zRzRzRzRzRzRzR** [comment]
check the demo in basic_demo/cli_demo_multi_gpus.py will help
