### ISSUE TITLE
在做文档类图片要素提取任务时，无中生有现象严重

### ISSUE THREAD

**Issue by starlxx** [THUDM/CogVLM2#118]
### System Info / 系統信息

python3

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1.在做合同等文档类图片要素提取任务时，有些没有任何要素的图片，会返回提取结果，结果基本都是无中生有的。

### Expected behavior / 期待表现

缓解无中生有问题

**Comment by iyuge2** [comment]
@starlxx hi，方便问一下，你用的是哪个模型版本吗？以及图片是中文还是英文的？

**Comment by zRzRzRzRzRzRzR** [comment]
最好能提供一下推理的环境，场景以及精度

**Comment by starlxx** [comment]
> @starlxx hi，方便问一下，你用的是哪个模型版本吗？以及图片是中文还是英文的？

用的是cogvlm2-llama3-chinese-chat-19B-int4这个模型，图片是中文的一些文档类图片，如合同等，发现在多页合同中，尤其是没有要素的页面，无中生有现象很严重。

**Comment by starlxx** [comment]
> 最好能提供一下推理的环境，场景以及精度，这可以帮助我们复现问题，感谢
用的是cogvlm2-llama3-chinese-chat-19B-int4这个模型，A100显卡，图片是中文的一些文档类图片，如合同等，发现在多页合同中，尤其是没有要素的页面，无中生有现象很严重。或者提问”这张图片里的甲方是不是xxx？”这样的问题，模型会倾向于回复“是”，即使问题中的xxx是错误的或不存在的。

**Comment by zRzRzRzRzRzRzR** [comment]
建议还是用BF16的版本，int4确实有一定的损失，目前没有相关的计划。
