### ISSUE TITLE
微调glm-4v-9B时的lora-target应该写什么？

### ISSUE THREAD

**Issue by Qinger27** [THUDM/CogVLM2#119]
使用peft_lora.py 运行，报错ValueError: Target modules {'vision_expert_query_key_value'} not found in the base model. Please check the target modules and try again. 请问对于 glm-4v-9B 模型，这个参数应该是什么？

**Comment by zRzRzRzRzRzRzR** [comment]
emm 这个是cogvlm的吧，9b的话或许你应该根据9B的代码看看？
目前我还没做到这个部分的适配

**Comment by Qinger27** [comment]
glm-4v-9B 不是你们发布的吗？不好意思啊，我以为你们是一个team😬

**Comment by zRzRzRzRzRzRzR** [comment]
这两个模型有一定的差距，少了视觉专家的部分，glm-4v-9b应该是用query_key_value，而且这两个代码应该不兼容，所以估计要重新做的

**Comment by Qinger27** [comment]
请问大概什么时候可以给一个finetune的脚本呀？非常期待你们的工作～

**Comment by zRzRzRzRzRzRzR** [comment]
glm-4v 9b已经更新微调代码

**Comment by Qinger27** [comment]
感谢～
