### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by wonderfulxin** [THUDM/CogVLM2#121]
### System Info / 系統信息

windows10

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

error   requests.exceptions.ReadTimeout: (ReadTimeoutError("HTTPSConnectionPool(host='cdn-lfs-us-1.huggingface.co', port=443): Read timed out. (read timeout
=10)"), '(Request ID: 96de49cd-fd9d-4b91-8df1-5cb1f510eaf8)')

### Expected behavior / 期待表现

error    requests.exceptions.ReadTimeout: (ReadTimeoutError("HTTPSConnectionPool(host='cdn-lfs-us-1.huggingface.co', port=443): Read timed out. (read timeout
=10)"), '(Request ID: 96de49cd-fd9d-4b91-8df1-5cb1f510eaf8)')

**Comment by zRzRzRzRzRzRzR** [comment]
直接用git下载模型吧

**Comment by wonderfulxin** [comment]
> 直接用git下载模型吧

host='cdn-lfs-us-1.huggingface.co', port=443 现在是这个连不上  我是用git 下载的
