### ISSUE TITLE
模型会有上下文的记忆功能吗？

### ISSUE THREAD

**Issue by cloudfool** [THUDM/CogVLM2#124]
我启动了openai_api_demo之后，使用openai_api_request经过多次测试后 持续测一张图片，答案都是相同的；但是等我重启了一下openai_api_demo, 再测那张图片，得到的答案变化很大；请问这是什么原因？  在模型启动过程中，之前的request会影响模型的下一次request的回答吗？

**Comment by zRzRzRzRzRzRzR** [comment]
这肯定没有啊，所有的上下文记忆都是通过 messages一次传入到模型的呀，模型是不会储存上下文的
