### ISSUE TITLE
cuda11.7 模型推理报错

### ISSUE THREAD

**Issue by wuys1** [THUDM/CogVLM2#126]
### System Info / 系統信息

Python：3.10.14
Cuda：11.7
torch：2.0.1
torchvision：0.15.2
xformers：0.0.22
transformers：4.42.3

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1、首先根据cuda11.7，安装torch==2.0.1 torchvision==0.15.2
2、注释掉requirements中的torch, torchvision, xformers，安装requirements.txt
3、手动安装xformers==0.0.22
4、执行CUDA_VISIBLE_DEVICES=3 python cli_demo.py
5、报错：
(py310-cogvlm) root@gpu-a800-01:/gpu/CogVLM2/basic_demo# CUDA_VISIBLE_DEVICES=3 python cli_demo.py

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.
Unused kwargs: ['_load_in_4bit', '_load_in_8bit', 'quant_method']. These kwargs are not used in <class 'transformers.utils.quantization_config.BitsAndBytesConfig'>.
/opt/anaconda3/envs/py310-cogvlm/lib/python3.10/site-packages/transformers/quantizers/auto.py:167: UserWarning: You passed `quantization_config` or equivalent parameters to `from_pretrained` but the model you're loading already has a `quantization_config` attribute. The `quantization_config` from the model will be used.
  warnings.warn(warning_msg)
/opt/anaconda3/envs/py310-cogvlm/lib/python3.10/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
image path >>>>>
You did not enter image path, the following will be a plain text conversation.
Human:introduce yourself
Traceback (most recent call last):
  File "/gpu/CogVLM2/basic_demo/cli_demo.py", line 102, in <module>
    outputs = model.generate(**inputs, **gen_kwargs)
  File "/opt/anaconda3/envs/py310-cogvlm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/opt/anaconda3/envs/py310-cogvlm/lib/python3.10/site-packages/transformers/generation/utils.py", line 1914, in generate
    result = self._sample(
  File "/opt/anaconda3/envs/py310-cogvlm/lib/python3.10/site-packages/transformers/generation/utils.py", line 2651, in _sample
    outputs = self(
  File "/opt/anaconda3/envs/py310-cogvlm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/anaconda3/envs/py310-cogvlm/lib/python3.10/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/cogvlm2-llama3-chinese-chat-19B-int4/modeling_cogvlm.py", line 620, in forward
    outputs = self.model(
  File "/opt/anaconda3/envs/py310-cogvlm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/anaconda3/envs/py310-cogvlm/lib/python3.10/site-packages/accelerate/hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/root/.cache/huggingface/modules/transformers_modules/cogvlm2-llama3-chinese-chat-19B-int4/modeling_cogvlm.py", line 402, in forward
    return self.llm_forward(
  File "/root/.cache/huggingface/modules/transformers_modules/cogvlm2-llama3-chinese-chat-19B-int4/modeling_cogvlm.py", line 451, in llm_forward
    past_key_values_length = past_key_values[0][0].shape[2]
AttributeError: 'str' object has no attribute 'shape'

### Expected behavior / 期待表现

排查定位问题原因

**Comment by 1stdinosaur** [comment]
> ### System Info / 系統信息
> Python：3.10.14 Cuda：11.7 torch：2.0.1 torchvision：0.15.2 xformers：0.0.22 transformers：4.42.3
> 
> ### Who can help? / 谁可以帮助到您？
> _No response_
> 
> ### Information / 问题信息
> * [x]  The official example scripts / 官方的示例脚本
> * [ ]  My own modified scripts / 我自己修改的脚本和任务
> 
> ### Reproduction / 复现过程
> 1、首先根据cuda11.7，安装torch==2.0.1 torchvision==0.15.2 2、注释掉requirements中的torch, torchvision, xformers，安装requirements.txt 3、手动安装xformers==0.0.22 4、执行CUDA_VISIBLE_DEVICES=3 python cli_demo.py 5、报错： (py310-cogvlm) root@gpu-a800-01:/gpu/CogVLM2/basic_demo# CUDA_VISIBLE_DEVICES=3 python cli_demo.py
> 
> Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained. Unused kwargs: ['_load_in_4bit', '_load_in_8bit', 'quant_method']. These kwargs are not used in <class 'transformers.utils.quantization_config.BitsAndBytesConfig'>. /opt/anaconda3/envs/py310-cogvlm/lib/python3.10/site-packages/transformers/quantizers/auto.py:167: UserWarning: You passed `quantization_config` or equivalent parameters to `from_pretrained` but the model you're loading already has a `quantization_config` attribute. The `quantization_config` from the model will be used. warnings.warn(warning_msg) /opt/anaconda3/envs/py310-cogvlm/lib/python3.10/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly. To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage() return self.fget.**get**(instance, owner)() image path >>>>> You did not enter image path, the following will be a plain text conversation. Human:introduce yourself Traceback (most recent call last): File "/gpu/CogVLM2/basic_demo/cli_demo.py", line 102, in outputs = model.generate(**inputs, **gen_kwargs) File "/opt/anaconda3/envs/py310-cogvlm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/opt/anaconda3/envs/py310-cogvlm/lib/python3.10/site-packages/transformers/generation/utils.py", line 1914, in generate result = self._sample( File "/opt/anaconda3/envs/py310-cogvlm/lib/python3.10/site-packages/transformers/generation/utils.py", line 2651, in _sample outputs = self( File "/opt/anaconda3/envs/py310-cogvlm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "/opt/anaconda3/envs/py310-cogvlm/lib/python3.10/site-packages/accelerate/hooks.py", line 166, in new_forward output = module._old_forward(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/cogvlm2-llama3-chinese-chat-19B-int4/modeling_cogvlm.py", line 620, in forward outputs = self.model( File "/opt/anaconda3/envs/py310-cogvlm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "/opt/anaconda3/envs/py310-cogvlm/lib/python3.10/site-packages/accelerate/hooks.py", line 166, in new_forward output = module._old_forward(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/cogvlm2-llama3-chinese-chat-19B-int4/modeling_cogvlm.py", line 402, in forward return self.llm_forward( File "/root/.cache/huggingface/modules/transformers_modules/cogvlm2-llama3-chinese-chat-19B-int4/modeling_cogvlm.py", line 451, in llm_forward past_key_values_length = past_key_values[0][0].shape[2] AttributeError: 'str' object has no attribute 'shape'
> 
> ### Expected behavior / 期待表现
> 排查定位问题原因

你好，应该是transformer版本的问题，4.42.x版本会出现这种错误，更换为4.40.1版本即可解决

**Comment by krutovvv** [comment]
Hello. I have the same issue, in the docker container nvidia/cuda:12.4.1-base-ubuntu22.04

**Comment by wuys1** [comment]
> > ### System Info / 系統信息
> > Python：3.10.14 Cuda：11.7 torch：2.0.1 torchvision：0.15.2 xformers：0.0.22 transformers：4.42.3
> > ### Who can help? / 谁可以帮助到您？
> > _No response_
> > ### Information / 问题信息
> > 
> > * [x]   The official example scripts / 官方的示例脚本
> > * [ ]   My own modified scripts / 我自己修改的脚本和任务
> > 
> > ### Reproduction / 复现过程
> > 1、首先根据cuda11.7，安装torch==2.0.1 torchvision==0.15.2 2、注释掉requirements中的torch, torchvision, xformers，安装requirements.txt 3、手动安装xformers==0.0.22 4、执行CUDA_VISIBLE_DEVICES=3 python cli_demo.py 5、报错： (py310-cogvlm) root@gpu-a800-01:/gpu/CogVLM2/basic_demo# CUDA_VISIBLE_DEVICES=3 python cli_demo.py
> > Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained. Unused kwargs: ['_load_in_4bit', '_load_in_8bit', 'quant_method']. These kwargs are not used in <class 'transformers.utils.quantization_config.BitsAndBytesConfig'>. /opt/anaconda3/envs/py310-cogvlm/lib/python3.10/site-packages/transformers/quantizers/auto.py:167: UserWarning: You passed `quantization_config` or equivalent parameters to `from_pretrained` but the model you're loading already has a `quantization_config` attribute. The `quantization_config` from the model will be used. warnings.warn(warning_msg) /opt/anaconda3/envs/py310-cogvlm/lib/python3.10/site-packages/torch/_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly. To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage() return self.fget.**get**(instance, owner)() image path >>>>> You did not enter image path, the following will be a plain text conversation. Human:introduce yourself Traceback (most recent call last): File "/gpu/CogVLM2/basic_demo/cli_demo.py", line 102, in outputs = model.generate(**inputs, **gen_kwargs) File "/opt/anaconda3/envs/py310-cogvlm/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs) File "/opt/anaconda3/envs/py310-cogvlm/lib/python3.10/site-packages/transformers/generation/utils.py", line 1914, in generate result = self._sample( File "/opt/anaconda3/envs/py310-cogvlm/lib/python3.10/site-packages/transformers/generation/utils.py", line 2651, in _sample outputs = self( File "/opt/anaconda3/envs/py310-cogvlm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "/opt/anaconda3/envs/py310-cogvlm/lib/python3.10/site-packages/accelerate/hooks.py", line 166, in new_forward output = module._old_forward(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/cogvlm2-llama3-chinese-chat-19B-int4/modeling_cogvlm.py", line 620, in forward outputs = self.model( File "/opt/anaconda3/envs/py310-cogvlm/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl return forward_call(*args, **kwargs) File "/opt/anaconda3/envs/py310-cogvlm/lib/python3.10/site-packages/accelerate/hooks.py", line 166, in new_forward output = module._old_forward(*args, **kwargs) File "/root/.cache/huggingface/modules/transformers_modules/cogvlm2-llama3-chinese-chat-19B-int4/modeling_cogvlm.py", line 402, in forward return self.llm_forward( File "/root/.cache/huggingface/modules/transformers_modules/cogvlm2-llama3-chinese-chat-19B-int4/modeling_cogvlm.py", line 451, in llm_forward past_key_values_length = past_key_values[0][0].shape[2] AttributeError: 'str' object has no attribute 'shape'
> > ### Expected behavior / 期待表现
> > 排查定位问题原因
> 
> 你好，应该是transformer版本的问题，4.42.x版本会出现这种错误，更换为4.40.1版本即可解决


感谢，更换后成功解决问题！
