### ISSUE TITLE
【text-generation-inference】Unsupported model type cogvlm2

### ISSUE THREAD

**Issue by ericzhou571** [THUDM/CogVLM2#127]
### System Info / 系統信息

A100
ghcr.io/huggingface/text-generation-inference:2.1.0

### Who can help? / 谁可以帮助到您？
@1049451037 

使用tgi部署的遇到报错
ValueError: Unsupported model type cogvlm2
使用的镜像为：ghcr.io/huggingface/text-generation-inference:2.1.0

Args {
    model_id: "/xxxx/THUDM/cogvlm2-llama3-chinese-chat-19B-tgi/",
    revision: None,
    validation_workers: 2,
    sharded: None,
    num_shard: None,
    quantize: None,
    speculate: None,
    dtype: None,
    **trust_remote_code: true,**
...    
trust_remote_code已经设置为true了，仍然报错  

在huggingface上也有人提出了类似的问题：
https://huggingface.co/THUDM/cogvlm2-llama3-chat-19B-tgi/discussions/1

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

详见：https://huggingface.co/THUDM/cogvlm2-llama3-chat-19B-tgi/discussions/1

### Expected behavior / 期待表现

正常部署

**Comment by ericzhou571** [comment]
很奇怪，在huggingface的main branch里没有见到cogvlm的模型，但是在tgi的版本里未见modeling_cogvlm_xxx.py的文件
![截屏2024-07-02 16 06 47](https://github.com/THUDM/CogVLM2/assets/57415741/1482da3e-575f-4bb4-b75b-2e80492b0536)
![截屏2024-07-02 16 10 13](https://github.com/THUDM/CogVLM2/assets/57415741/8e6ae357-b5e3-4690-a50e-84d3c63283de)

请问tgi版本是有其他load模型代码的方式嘛？

**Comment by zRzRzRzRzRzRzR** [comment]
tgi的调用方案不需要这些吧，我们提供了构建景象的办法，或许可以看一下我们的技术文档

**Comment by xzhou42** [comment]
> tgi的调用方案不需要这些吧，我们提供了构建景象的办法，或许可以看一下我们的技术文档

@zRzRzRzRzRzRzR 
遇到了相同的问题，看了TGI的代码里并没有匹配上model_type:"cogvlm2", 请问目前有解决方案吗

**Comment by joel-simp** [comment]
Facing similar error ValueError: Unsupported model type cogvlm2
I tried to run other models using TGI, and it seems cogvlm2 don't seem to work with the same code
