### ISSUE TITLE
能否实现版式复杂多变的表格类的图像的关键信息抽取任务

### ISSUE THREAD

**Issue by kkiskkk** [THUDM/CogVLM2#13]
### Feature request  / 功能建议

类似于下图：
（来自开放数据集）

使用demo会返回几对关键信息对但是如果想要所有的关键信息是否需要针对特定数据集微调？ 这个示例只是简单的版式。

### Motivation / 动机

无

### Your contribution / 您的贡献

无

**Comment by mactavish91** [comment]
你好，示例似乎没上传成功

**Comment by zRzRzRzRzRzRzR** [comment]
要微调的，但是抽取能力和OCR能力是非常不错的
