### ISSUE TITLE
'str' object has no attribute 'shape' int4 model

### ISSUE THREAD

**Issue by KirilAngelov** [THUDM/CogVLM2#134]
### System Info / 系統信息

pytorch : 2.1.0
python : 3.10
cuda : 11.8.0
ubuntu : 22.04
GPU : NVIDIA A40 48 GB VRAM

I'm running the code using Jupyter Notebook connected to a cloud instance of A40 GPU. 

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

1. Go to https://huggingface.co/THUDM/cogvlm2-llama3-chat-19B-int4
2. Copy and paste the quick start script in your environment
3. Install the required libraries from requirements.txt
4. Run the model

This is what happens when you run the model:
![image](https://github.com/THUDM/CogVLM2/assets/44143480/9db190ab-aef6-4316-afe2-bb5772785931)

### Expected behavior / 期待表现

The expected behavior should be the model running with the official example from huggingface and A40 GPU with 48 GB VRAM.

**Comment by huangshiyu13** [comment]
try this:
 `pip install transformer==4.40`
