### ISSUE TITLE
多显卡加载失败,在使用4张14.8G的显卡时,运行cli_demo_multi_gpus.py显存溢出

### ISSUE THREAD

**Issue by atlasroben** [THUDM/CogVLM2#136]
### System Info / 系統信息

4卡TESLA T4,每张显卡14.80GB显存,
torch 2.2.2
cu121
py 3.11.9

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

运行cli_demo_multi_gpus.py代码,在加载模型到第三张卡的时候显存溢出,第三张卡加载超过了14G
device_map['model.vision.transformer.layers.5']=3
device_map['model.vision.transformer.layers.6']=3
device_map['model.vision.transformer.layers.7']=3
device_map['model.vision.transformer.layers.8.input_layernorm']=3
我尝试直接修改device_map,将一部分末端层放到第四张显卡加载顺利了,但推理的时候崩了

### Expected behavior / 期待表现

能修复一下吗?谢谢

**Comment by zRzRzRzRzRzRzR** [comment]
在readme提到了每张卡一定要超过16G，因为部分视觉模块需要占用一个完整的空间

**Comment by atlasroben** [comment]
> 在readme提到了每张卡一定要超过16G，因为部分视觉模块需要占用一个完整的空间

谢谢您的回复,
