### ISSUE TITLE
ERROR: Cannot install -r basic_demo/requirements.txt (line 7) and uvicorn>=0.29.0 because these package versions have conflicting dependencies.

### ISSUE THREAD

**Issue by Xiongjiba** [THUDM/CogVLM2#14]
### System Info / 系統信息

用conda创建的新环境，python=3.11，CUDA=12.1，报以上错误QAQ

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

git clone后用conda创建python=3.11的环境，pip install -r requirement.txt后出现以下报错：

ERROR: Cannot install -r basic_demo/requirements.txt (line 7) and uvicorn>=0.29.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested uvicorn>=0.29.0
    chainlit 1.1.101 depends on uvicorn<0.26.0 and >=0.25.0
    The user requested uvicorn>=0.29.0
    chainlit 1.1.0 depends on uvicorn<0.26.0 and >=0.25.0
    The user requested uvicorn>=0.29.0
    chainlit 1.0.506 depends on uvicorn<0.26.0 and >=0.25.0

### Expected behavior / 期待表现

能解决这个问题

**Comment by zRzRzRzRzRzRzR** [comment]
收到，chainlit为准

**Comment by zRzRzRzRzRzRzR** [comment]
已经解决
