### ISSUE TITLE
cogvlm2-grounding版本会有多个目标输出吗？很期待

### ISSUE THREAD

**Issue by qinzhenyi1314** [THUDM/CogVLM2#17]
### Feature request  / 功能建议

看之前的issue后续是有cogvlm2-grounding版本，想请问下会有多个目标输出吗？

### Motivation / 动机

一个图片里同属性的目标会有多个，但是cogvlm-grounding只能出一个目标。后续的cogcom有多个目标输出，cogvlm2-grounding版本会多个目标输出吗？

**Comment by zRzRzRzRzRzRzR** [comment]
会有推出相关版本的计划
