### ISSUE TITLE
CogVLM2 Videos demo  CUDA_VISIBLE_DEVICES=0 python cli_video_demo.py --quant 4

### ISSUE THREAD

**Issue by wangke5437** [THUDM/CogVLM2#176]
### System Info / 系統信息

Package                                  Version
---------------------------------------- ------------------
accelerate                               0.33.0
aiofiles                                 23.2.1
annotated-types                          0.7.0
anyio                                    3.7.1
asyncer                                  0.0.2
av                                       12.3.0
bidict                                   0.23.1
bitsandbytes                             0.43.3
blinker                                  1.8.2
certifi                                  2024.7.4
chainlit                                 1.1.400
charset-normalizer                       3.3.2
chevron                                  0.14.0
click                                    8.1.7
contourpy                                1.2.1
cycler                                   0.12.1
dataclasses-json                         0.5.14
decord                                   0.6.0
Deprecated                               1.2.14
distro                                   1.9.0
einops                                   0.8.0
exceptiongroup                           1.2.2
fastapi                                  0.110.3
ffmpy                                    0.4.0
filelock                                 3.15.4
filetype                                 1.2.0
Flask                                    3.0.3
fonttools                                4.53.1
fsspec                                   2024.6.1
fvcore                                   0.1.5.post20221221
gevent                                   24.2.1
googleapis-common-protos                 1.63.2
gradio                                   4.39.0
gradio_client                            1.1.1
greenlet                                 3.0.3
grpcio                                   1.65.1
gunicorn                                 22.0.0
h11                                      0.14.0
httpcore                                 1.0.5
httpx                                    0.27.0
huggingface-hub                          0.24.3
idna                                     3.7
importlib_metadata                       8.0.0
importlib_resources                      6.4.0
iopath                                   0.1.10
itsdangerous                             2.2.0
Jinja2                                   3.1.4
kiwisolver                               1.4.5
Lazify                                   0.4.0
literalai                                0.0.607
loguru                                   0.7.2
markdown-it-py                           3.0.0
MarkupSafe                               2.1.5
marshmallow                              3.21.3
matplotlib                               3.9.1
mdurl                                    0.1.2
mpmath                                   1.3.0
mypy-extensions                          1.0.0
nest-asyncio                             1.6.0
networkx                                 3.3
numpy                                    1.26.4
nvidia-cublas-cu12                       12.1.3.1
nvidia-cuda-cupti-cu12                   12.1.105
nvidia-cuda-nvrtc-cu12                   12.1.105
nvidia-cuda-runtime-cu12                 12.1.105
nvidia-cudnn-cu12                        8.9.2.26
nvidia-cufft-cu12                        11.0.2.54
nvidia-curand-cu12                       10.3.2.106
nvidia-cusolver-cu12                     11.4.5.107
nvidia-cusparse-cu12                     12.1.0.106
nvidia-nccl-cu12                         2.18.1
nvidia-nvjitlink-cu12                    12.5.82
nvidia-nvtx-cu12                         12.1.105
openai                                   1.37.1
opencv-python                            4.10.0.84
opentelemetry-api                        1.26.0
opentelemetry-exporter-otlp              1.26.0
opentelemetry-exporter-otlp-proto-common 1.26.0
opentelemetry-exporter-otlp-proto-grpc   1.26.0
opentelemetry-exporter-otlp-proto-http   1.26.0
opentelemetry-instrumentation            0.47b0
opentelemetry-proto                      1.26.0
opentelemetry-sdk                        1.26.0
opentelemetry-semantic-conventions       0.47b0
orjson                                   3.10.6
packaging                                23.2
pandas                                   2.2.2
parameterized                            0.9.0
pillow                                   10.4.0
pip                                      24.0
portalocker                              2.10.1
protobuf                                 4.25.4
psutil                                   6.0.0
pydantic                                 2.8.2
pydantic_core                            2.20.1
pydub                                    0.25.1
Pygments                                 2.18.0
PyJWT                                    2.8.0
pyparsing                                3.1.2
python-dateutil                          2.9.0.post0
python-dotenv                            1.0.1
python-engineio                          4.9.1
python-multipart                         0.0.9
python-socketio                          5.11.3
pytorchvideo                             0.1.5
pytz                                     2024.1
PyYAML                                   6.0.1
regex                                    2024.7.24
requests                                 2.32.3
rich                                     13.7.1
ruff                                     0.5.5
safetensors                              0.4.3
semantic-version                         2.10.0
setuptools                               69.5.1
shellingham                              1.5.4
simple-websocket                         1.0.0
six                                      1.16.0
sniffio                                  1.3.1
sse-starlette                            2.1.2
starlette                                0.37.2
sympy                                    1.13.1
syncer                                   2.0.3
tabulate                                 0.9.0
termcolor                                2.4.0
timm                                     1.0.8
tokenizers                               0.19.1
tomli                                    2.0.1
tomlkit                                  0.12.0
torch                                    2.1.0
torchvision                              0.16.0
tqdm                                     4.66.4
transformers                             4.40.0
triton                                   2.1.0
typer                                    0.12.3
typing_extensions                        4.12.2
typing-inspect                           0.9.0
tzdata                                   2024.1
uptrace                                  1.26.0
urllib3                                  2.2.2
uvicorn                                  0.25.0
watchfiles                               0.20.0
websockets                               11.0.3
Werkzeug                                 3.0.3
wheel                                    0.43.0
wrapt                                    1.16.0
wsproto                                  1.2.0
xformers                                 0.0.22.post7
yacs                                     0.1.8
zipp                                     3.19.2
zope.event                               5.0
zope.interface                           6.4.post2

### Who can help? / 谁可以帮助到您？

@zr

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

V100 16G显卡，没有任何修改，直接执行CUDA_VISIBLE_DEVICES=0 python cli_video_demo.py --quant 4

using with chat model
video path >>>>> /home/root123/桌面/autodetect/CogVLM2/resources/videos/basketball.mp4 
Human:
Traceback (most recent call last):
  File "/home/root123/桌面/autodetect/CogVLM2/video_demo/cli_video_demo.py", line 135, in <module>
    outputs = model.generate(**inputs, **gen_kwargs)
  File "/home/root123/.conda/envs/autodetect/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/root123/.conda/envs/autodetect/lib/python3.10/site-packages/transformers/generation/utils.py", line 1622, in generate
    result = self._sample(
  File "/home/root123/.conda/envs/autodetect/lib/python3.10/site-packages/transformers/generation/utils.py", line 2841, in _sample
    model_kwargs = self._update_model_kwargs_for_generation(
  File "/home/root123/.cache/huggingface/modules/transformers_modules/THUDM/cogvlm2-video-llama3-chat/f375ead7d8202ebe2c3d09f1068abdddeb2929fa/modeling_cogvlm.py", line 726, in _update_model_kwargs_for_generation
    cache_name, cache = self._extract_past_from_model_output(
ValueError: too many values to unpack (expected 2)

### Expected behavior / 期待表现

nothing

**Comment by huangshiyu13** [comment]
try `pip install transformers==4.42.4`

**Comment by wangke5437** [comment]
> try `pip install transformers==4.42.4`

完美解决，感谢
