### ISSUE TITLE
cogvlm2-video chat模式如何更改推理的帧数？

### ISSUE THREAD

**Issue by zhengxingmao** [THUDM/CogVLM2#196]
比如我的视频有5秒，每秒25帧，5秒总共125帧，按照目前逻辑只能取到6帧，会丢失一些信息，那么我如果自定义取的帧数呢？比如取8帧，12帧，24帧
https://github.com/THUDM/CogVLM2/blob/cf9cb3c60a871e0c8e5bde7feaf642e3021153e6/video_demo/inference.py#L40

**Comment by zhengxingmao** [comment]
@huangshiyu13  感谢你的回复，base 模型就不能对话了，希望能够给出对话模型的均匀抽帧的方式。

**Comment by huangshiyu13** [comment]
> @huangshiyu13 感谢你的回复，base 模型就不能对话了，希望能够给出对话模型的均匀抽帧的方式。

不是改成base模型，意思是你用这个base的抽帧方式
