### ISSUE TITLE
Quantized Models

### ISSUE THREAD

**Issue by nousr** [THUDM/CogVLM2#2]
### Feature request  / 功能建议

The readme mentions the existence of a INT4 version of the model -- i'm curious when it is planned on being released?

### Motivation / 动机

Having a quantized model will increase inference efficiency.

### Your contribution / 您的贡献

n/a

**Comment by zRzRzRzRzRzRzR** [comment]
已经在排期，我们会尽快推出

**Comment by QwertyJack** [comment]
You can use `bitsandbytes` to quantize the model on the fly:

```python
# install bitsandbytes: pip install bitsandbytes

...
# load model
model = AutoModelForCausalLM.from_pretrained(
        MODEL_PATH,
        trust_remote_code=True,
        torch_dtype=torch_type,
        device_map='auto',
        load_in_4bit=True,
)
...
```

**Comment by zRzRzRzRzRzRzR** [comment]
这是可以的，我们之后也会发布int4版本

**Comment by kele527** [comment]
> 这是可以的，我们之后也会发布int4版本

int4版本你们已经推出了，非常棒！现在是否可以尽快推出ollama版本？ 期待！

**Comment by BruceJust** [comment]
会考虑推出awq的量化代码吗？
从我们实测看，bitsandbytes量化并不能提高推理速度，只是节约了显存

**Comment by grigio** [comment]
How is possible to use on Ollama ? is GGUF supported ?

**Comment by okwinds** [comment]
求int8版本 🌹

**Comment by chuangzhidan** [comment]
> Reference
这里的on the fly是什么意思
