### ISSUE TITLE
int4 cli_demo run

### ISSUE THREAD

**Issue by gehong-coder** [THUDM/CogVLM2#21]
### System Info / 系統信息

python:3.11
xformers :0.0.26.post1
transformers: 4.41.0

model = AutoModelForCausalLM.from_pretrained(
    MODEL_PATH,
    torch_dtype=TORCH_TYPE,
    trust_remote_code=True,
    load_in_4bit=True,
    low_cpu_mem_usage=True
).to(DEVICE).eval()
错误：
`.to` is not supported for `4-bit` or `8-bit` bitsandbytes models. Please use the model as it is, since the model has already been set to the correct devices and casted to the correct `dtype`

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

CUDA_VISIBLE_DEVICES=0 python cli_demo.py

### Expected behavior / 期待表现

如何运行int4版本

**Comment by 1049451037** [comment]
Just remove `.to(DEVICE)` if you want to use int4.

**Comment by zRzRzRzRzRzRzR** [comment]
<img width="587" alt="image" src="https://github.com/THUDM/CogVLM2/assets/93239683/bfe66580-fe2e-48a9-a224-22aa50a1cb6f">

**Comment by gehong-coder** [comment]
好的已经解决谢谢

**Comment by blacksmithmf** [comment]
求助，我也遇到了相同的问题
torch==2.0.1 
torchvision==0.15.2 
torchaudio==2.0.2
triton-2.0.0
xformers==0.0.22
transformers==4.40
windows系统 ，CUDA 12.0

已经把cli_demo 里面的.to 相关的都去掉了，还是报错 
ValueError: `.to` is not supported for `4-bit` or `8-bit` bitsandbytes models. Please use the model as it is, since the model has already been set to the correct devices and casted to the correct `dtype`

**Comment by XuJianzhi** [comment]
> 求助，我也遇到了相同的问题 torch==2.0.1 torchvision==0.15.2 torchaudio==2.0.2 triton-2.0.0 xformers==0.0.22 transformers==4.40 windows系统 ，CUDA 12.0
> 
> 已经把cli_demo 里面的.to 相关的都去掉了，还是报错 ValueError: `.to` is not supported for `4-bit` or `8-bit` bitsandbytes models. Please use the model as it is, since the model has already been set to the correct devices and casted to the correct `dtype`

请问解决了吗
