### ISSUE TITLE
求快点出GGUF版本！

### ISSUE THREAD

**Issue by mrguo6221** [THUDM/CogVLM2#22]
### Feature request  / 功能建议

建议尽快推出GGUF版本

### Motivation / 动机

方便本地部署

### Your contribution / 您的贡献

无

**Comment by zRzRzRzRzRzRzR** [comment]
模型结构上暂时不会出gguf，同时，目前在适配llamacpp，ollama上都会遇到较大困难，短期不会有相关的动作
