### ISSUE TITLE
report or any docs

### ISSUE THREAD

**Issue by bpwl0121** [THUDM/CogVLM2#24]
hi,
thanks for your awesome work!
any report or docs can be helpful

thanks

**Comment by zRzRzRzRzRzRzR** [comment]
The model is similar to the previous generation of the open-source CogVLM model but uses more data and the latest llama3-8b as the LLM. If you find our work helpful, you can find citations at the bottom of the README.

**Comment by bpwl0121** [comment]
thanks for your reply.
you still use the arch like 
![image](https://github.com/THUDM/CogVLM2/assets/38959389/e6972efc-f1de-4918-aeae-bdea1870c834)'
great work！

since current most work follow the arch like llava，haha
