### ISSUE TITLE
支持 VLLM 推理加速

### ISSUE THREAD

**Issue by thesby** [THUDM/CogVLM2#25]
### Feature request  / 功能建议

希望 [CogVLM2](https://github.com/THUDM/CogVLM2) 能够支持 vllm 推理加速

### Motivation / 动机

推理速度更快

### Your contribution / 您的贡献

https://github.com/vllm-project/vllm

**Comment by zRzRzRzRzRzRzR** [comment]
正在计划中，需要一段时间

**Comment by Sushaokun** [comment]
好期待。
