### ISSUE TITLE
请问CogVLM2是否支持多卡微调？

### ISSUE THREAD

**Issue by wangdong1992** [THUDM/CogVLM2#27]
### Feature request  / 功能建议

目前打算在V100 16G 4卡微调，但是报错，推理没有问题。
https://github.com/THUDM/CogVLM2/blob/main/finetune_demo/README_zh.md
根据教程，需要每张显卡显存大于57G，请问后面是否可以支持多卡微调？

### Motivation / 动机

多卡微调

### Your contribution / 您的贡献

无

**Comment by zRzRzRzRzRzRzR** [comment]
模型forward没有做zero3的适配，要自己改模型结构
另外， 57G微调的是语言模型，vit部分已经冻结了，是微调不了视觉模型的

**Comment by Sleepychord** [comment]
@zRzRzRzRzRzRzR 为啥非要zero3？

**Comment by zRzRzRzRzRzRzR** [comment]
> @zRzRzRzRzRzRzR 为啥非要zero3？

zero2 只能做lm_head, vit的话80G显存不够，调不了，目测是微调代码可能还需要进一步优化

**Comment by tandakun** [comment]
大神，有计划未来给个能通过zeros3进行sft的模型和指南吗？我们算力内存8*16G

**Comment by zRzRzRzRzRzRzR** [comment]
我们在努力，但是目前这个模型微调的话需要的显存实在太大，8卡A100都没通

**Comment by tiandazhao** [comment]
> 模型forward没有做zero3的适配，要自己改模型结构 另外， 57G微调的是语言模型，vit部分已经冻结了，是微调不了视觉模型的

如何改模型结构来适配zero3呢，各位有没有好的办法？

**Comment by chensongcan** [comment]
> 我们在努力，但是目前这个模型微调的话需要的显存实在太大，8卡A100都没通

你好，请问当前的代码支持多机多卡训练吗

**Comment by zRzRzRzRzRzRzR** [comment]
不支持zero3，相关的修改我们还没改，支持多机多卡，但是每张卡需要70G以上显存

**Comment by chuangzhidan** [comment]
> 不支持zero3，相关的修改我们还没改，支持多机多卡，但是每张卡需要70G以上显存

【使用零冗余优化策略2（zero2）时，至少需要73GB的GPU内存，并且需要8个GPU。  】
是说lora zero2微调需要的显存为：73GB*8=584GB吗？

【····'labels_en')  # or 'labels_zh' or 'labels' 可以自行修改】
这里如果是labels标识包括中英一起的？

谢谢

**Comment by supersteve2001** [comment]
> ### Feature request / 功能建议
> 目前打算在V100 16G 4卡微调，但是报错，推理没有问题。 https://github.com/THUDM/CogVLM2/blob/main/finetune_demo/README_zh.md 根据教程，需要每张显卡显存大于57G，请问后面是否可以支持多卡微调？
> 
> ### Motivation / 动机
> 多卡微调
> 
> ### Your contribution / 您的贡献
> 无

hello，我目前正在用v100部署cogvlm2，可是输出稳定是：Floating point exception(core dumped)。之前在4090单卡上部署int4模型没有问题
我想请问您在v100部署时有无不同之处

**Comment by guyuchao** [comment]
如何改模型结构来适配zero3呢，大概需要改哪些东西。
