### ISSUE TITLE
CogVLM2 在 昇腾npu服务器上由于triton安装不了无法运行

### ISSUE THREAD

**Issue by fallbernana123456** [THUDM/CogVLM2#28]
### System Info / 系統信息

架构： ARM 架构
NPU：昇腾910B
python:3.10.12

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

由于在昇腾服务器上无法安装triton ，运行不起来。

### Expected behavior / 期待表现

希望能支持NPU服务器的运行

**Comment by zRzRzRzRzRzRzR** [comment]
依赖triton，这个确实兼容不了，需要在Linux系统 + NV显卡跑

**Comment by aistream69** [comment]
作为一家国产GPU厂商，triton编译的支持还在开发中，我们也遇到同样问题了，现在除了nv，也有很多其他GPU可选了，官方是否考虑出一个不依赖triton.jit的rotary_kernel函数？
