### ISSUE TITLE
预训练代码

### ISSUE THREAD

**Issue by JianbangZ** [THUDM/CogVLM2#3]
### Feature request  / 功能建议

请问打算开放预训练代码吗？想尝试用些稍微小点的visual encoder或者换换不同的LLM backbone试试效果

### Motivation / 动机

用不同的LLM backbone AND/PR visual encoder 训练

### Your contribution / 您的贡献

N/A

**Comment by zRzRzRzRzRzRzR** [comment]
没有哦😧
