### ISSUE TITLE
微调效果不理想，测试微调后的模型感觉完全没学到东西，同一批数据，效果低于cogvlm和cogagent

### ISSUE THREAD

**Issue by Guodashen222** [THUDM/CogVLM2#30]
看日志 感觉非常抽象 这个是啥原因 
![b898fe03b25b1bea295cb54b1433fcb](https://github.com/THUDM/CogVLM2/assets/93236115/e385758f-e2b9-40be-96c9-0918e3905e47)

**Comment by Guodashen222** [comment]
几乎没有修改
![60451d064a0c4c29c2a97fdf2565747](https://github.com/THUDM/CogVLM2/assets/93236115/9ebd7c91-cd43-4263-8a4c-430c0423ff55)

**Comment by Sleepychord** [comment]
1 . batch size=1 是不是有点少；2. 我们最近会安排同学验证一下微调接口正确性。

**Comment by Guodashen222** [comment]
> 1 . batch size=1 是不是有点少；2. 我们最近会安排同学验证一下微调接口正确性。

试过其他大小 最终结果区别不大

**Comment by zRzRzRzRzRzRzR** [comment]
现在微调target的是 lm_head  VIT是没动的

**Comment by Guodashen222** [comment]
> 现在微调target的是 lm_head VIT是没动的，这个日志。。。确实抽象，检查一下

  我想着针对其他线形层进行微调 例如lora_target_layers = [
    "model.vision.transformer.layers.45.attention.dense",
    "model.vision.transformer.layers.45.attention.query_key_value",
    "model.vision.transformer.layers.45.mlp.fc1",
    "model.vision.transformer.layers.45.mlp.fc2",
    "model.vision.transformer.layers.46.attention.dense",
    "model.vision.transformer.layers.46.attention.query_key_value",
    "model.vision.transformer.layers.46.mlp.fc1",
    "model.vision.transformer.layers.46.mlp.fc2",
    "model.vision.transformer.layers.47.attention.dense",
    "model.vision.transformer.layers.47.attention.query_key_value",
    "model.vision.transformer.layers.47.mlp.fc1",
    "model.vision.transformer.layers.47.mlp.fc2",
    "model.vision.transformer.layers.48.attention.dense",
    "model.vision.transformer.layers.48.attention.query_key_value",
    "model.vision.transformer.layers.48.mlp.fc1",
    "model.vision.transformer.layers.48.mlp.fc2",
    "model.vision.transformer.layers.49.attention.dense"]
    请问一下，如果我只想得到一个解决特定领域问题的模型。”从pre-train模型开始SFT训练，先做CPT，SFT数据使用领域数据“，这种方式是不是最好的呢？

**Comment by Guodashen222** [comment]
> 现在微调target的是 lm_head VIT是没动的，这个日志。。。确实抽象，检查一下

如果加入vit微调 80g显存不够用 看来代码还需要优化

**Comment by zRzRzRzRzRzRzR** [comment]
调不动的，我们正在尝试优化代码，根据这个模型结构直接lora是调不动的

**Comment by Guodashen222** [comment]
> 调不动的，我们正在尝试优化代码，根据这个模型结构直接lora是调不动vit的，现在的分辨率是1344x 1344 ，而不是1代的490
> 
> 同时，微调的框架从开发组熟悉的SAT换到了HF，目前排查的微调需要的显存太高，还在优化中

我这边资源充足 有很多数据集 有需要我们可以测试新的微调代码 这是我的邮箱colosslise@gmail.com

**Comment by Helens1997** [comment]
> > 1 . batch size=1 是不是有点少；2. 我们最近会安排同学验证一下微调接口正确性。
> 
> 试过其他大小 最终结果区别不大

请问这个后面解决了嘛？
