### ISSUE TITLE
cuda版本

### ISSUE THREAD

**Issue by samaritan1998** [THUDM/CogVLM2#31]
请问cuda11.8支持么？ 安装requirements.txt之后会报错
![image](https://github.com/THUDM/CogVLM2/assets/48083986/cfe427a8-c58d-47f6-802a-143f419f72d2)

**Comment by zRzRzRzRzRzRzR** [comment]
torch2.3.0+cu121尝试一下

**Comment by samaritan1998** [comment]
还是不行，能不能提供一个镜像呢

**Comment by qinzhenyi1314** [comment]
同问，cogvlm本事可以正常跑的环境（cuda11.8），我看cogvlm2的依赖项基本上和cogvlm差不多，然后运行显示Triton报错
RuntimeError: Triton Error [CUDA]: device kernel image is invalid

**Comment by qinzhenyi1314** [comment]
> torch2.3.0+cu121尝试一下

服务器限制，不能升级驱动，不能使用cu121，之前cogvlm使用cuda11.8是可以的，新的cogvlm2 ，同样的环境
RuntimeError: Triton Error [CUDA]: device kernel image is invalid

**Comment by zRzRzRzRzRzRzR** [comment]
https://github.com/THUDM/CogVLM2/issues/32#issuecomment-2132868819
