### ISSUE TITLE
安防场景下使用

### ISSUE THREAD

**Issue by 77h2l** [THUDM/CogVLM2#35]
### Feature request  / 功能建议

-

### Motivation / 动机

hi there,请问一下当前版本的多模态大模型在识别安防or真实open场景下的要素和事件的准确度如何，是否有相关的指标可以直接or间接反映模型的能力，以及应用上有什么建议，谢谢。

### Your contribution / 您的贡献

-

**Comment by zRzRzRzRzRzRzR** [comment]
您可以在我们的readme中看到相关榜单的指标

实际应用上，cogvlm在ocr能力更强，同时，对视觉场景的理解能力相较于1代有提升，可以完成一些传统ocr难以完成的混合视觉任务（象形文字识别，非规则字体文件的扫描）

**Comment by 77h2l** [comment]
> 您可以在我们的readme中看到相关榜单的指标
> 
> 实际应用上，cogvlm在ocr能力更强，同时，对视觉场景的理解能力相较于1代有提升，可以完成一些传统ocr难以完成的混合视觉任务（象形文字识别，非规则字体文件的扫描）

感谢回复哈，请问具体是哪一个数据集的指标呢。。：）

**Comment by zRzRzRzRzRzRzR** [comment]
在readme中横轴的这些榜单指标
<img width="592" alt="image" src="https://github.com/THUDM/CogVLM2/assets/93239683/665600d0-12da-4de8-88e6-ba17efe49e52">
