### ISSUE TITLE
Does the visual model freeze during the pre-training phase?

### ISSUE THREAD

**Issue by paulpaul91** [THUDM/CogVLM2#38]
Does the visual model freeze during the pre-training phase?

**Comment by zRzRzRzRzRzRzR** [comment]
activate

**Comment by paulpaul91** [comment]
> activate
从checkpoint上来看，vit 用的是EVA02-4B的模型，模型输入分辨率支持1344*1344，说position_id肯定走了插值，想问下EVA02这块的改动，是怎么自适应的？是EVA02-4B单走了CLIP训练，还是说多模态时VIT unfreeze直接硬训EVA02的position-id?
