### ISSUE TITLE
微调的模型不支持中文的模型吗？

### ISSUE THREAD

**Issue by Guodashen222** [THUDM/CogVLM2#41]
![792d52f13d651c5c8ce761f78fedccf](https://github.com/THUDM/CogVLM2/assets/93236115/06d76f8b-d664-45b5-8f53-26d303791bb5)
使用八个a800无法完成对中文模型微调的任务

**Comment by zRzRzRzRzRzRzR** [comment]
直接用中文模型微调，支持中文的

**Comment by Guodashen222** [comment]
> 直接用中文模型微调，支持中文的

但是为什么会出现这个显存不足的问题呢

**Comment by tiandazhao** [comment]
我也遇到了同样的问题，中文模型会出现OOM

**Comment by zRzRzRzRzRzRzR** [comment]
更新了最新的hf 代码和微调代码了吗，发个配置？我这边微调是正常的

**Comment by whbzju** [comment]
> 更新了最新的hf 代码和微调代码了吗，发个配置？我这边微调是正常的

同遇到A800 80G 8卡oom，你们cuda是什么版本

**Comment by zRzRzRzRzRzRzR** [comment]
cuda12.3 记得拉最新的hf中的modeling_cogvlm

**Comment by whbzju** [comment]
> cuda12.3 记得拉最新的hf中的modeling_cogvlm

非常感谢回复，马上去试下，现在用的是modelscope的版本

**Comment by whbzju** [comment]
麻烦也更新下modelscope的modeling_cogvlm吧，确实是这个问题
