### ISSUE TITLE
Support text input only

### ISSUE THREAD

**Issue by BrianXiao1** [THUDM/CogVLM2#46]
Congraduations. After experience your online demo and view your official docs, I want know that whether it support text input only or not. Is the language model available for chatting?

**Comment by Sleepychord** [comment]
just press `enter` without typing in anything in `cli_demo.py` when prompting "image path >>>>>".

**Comment by BrianXiao1** [comment]
thx!

**Comment by Sleepychord** [comment]
Seems like the answer is strange. I will look into it.

**Comment by BrianXiao1** [comment]
I mean, in your streamlit demo, It requires me to upload an image to start. So can I start without upload an image at first?
