### ISSUE TITLE
是否可以支持设置stop words？

### ISSUE THREAD

**Issue by xuexidi** [THUDM/CogVLM2#54]
### Feature request  / 功能建议

当前basic_demo里的opanai_api_demo.py里是基于`model.generate`来生成模型推理结果，但是`model.generate`貌似没有类似`stop_words_ids`的参数来控制输出及时停止(？)，请问如何才能实现该功能？

另外，请问CogVLM2模型有无方法可以部署加速推理？（类似vllm、lmdeploy，不过这两个框架目前貌似不支持CogVLM系列模型部署加速）

谢谢！

### Motivation / 动机

想让模型输出CoT，又不想模型额外输出过多的东西影响推理耗时，所以想设置关键词提前停止模型生成

### Your contribution / 您的贡献

暂无~

**Comment by zRzRzRzRzRzRzR** [comment]
vllm正在做。
可以使用stop word ，根hf的stop id是一样的，要自己在generate的时候加入这个参数

**Comment by xuexidi** [comment]
非常感谢~，期待vllm版本出来


另外，我今天早些时候确实查阅到资料，自行修改了一些代码，实现了stop words逻辑~


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年05月28日 18:40 |
| 收件人 | THUDM/CogVLM2 ***@***.***> |
| 抄送人 | xuexidi ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [THUDM/CogVLM2] 是否可以支持设置stop words？ (Issue #54) |

vllm正在做。
可以使用stop word ，根hf的stop id是一样的，要自己在generate的时候加入这个参数
