### ISSUE TITLE
int4  cli demo error

### ISSUE THREAD

**Issue by valencebond** [THUDM/CogVLM2#57]
we meet the following case

<img width="1272" alt="image" src="https://github.com/THUDM/CogVLM2/assets/44313446/8e8344f1-fc56-45a2-8749-54f95635e415">

**Comment by cuppersd** [comment]
Floating point exception (core dumped)同样报错，跑不起来

**Comment by zRzRzRzRzRzRzR** [comment]
啥依赖和硬件配置呢
