### ISSUE TITLE
int4 cli_demo_multi_gpus OutOfMemoryError

### ISSUE THREAD

**Issue by CanvaChen** [THUDM/CogVLM2#58]
修改max_memory_per_gpu = "11GiB"
```bash
python basic_demo/cli_demo_multi_gpus.py
```

使用两张12G显卡运行cogvlm2-llama3-chinese-chat-19B-int4模型，报错：
> torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 1002.00 MiB. GPU

**Comment by Jack-Yang-S** [comment]
加载模型那一步就会出错，其实加载了两次，第一次并没有分布式加载，单个gpu必须大于16g，但是我把第一次加载分布式后，还是会报错，在推理的时候报错

**Comment by zRzRzRzRzRzRzR** [comment]
请查看文档，一定需要保证单张显卡超过16G。
关于你说的第一次的加载分布什么意思。需要错误信息
