### ISSUE TITLE
CogVLM2的坐标定位能力如何

### ISSUE THREAD

**Issue by fang-h** [THUDM/CogVLM2#6]
CogVLM2还是像CogVLM以及CogAgent都具有很强的坐标定位能力嘛？没有看到相关技术文档说明或者使用示例。

**Comment by Sleepychord** [comment]
我们将逐步放出cogvlm2-grounding版本，目前是仅chat版本，敬请期待。

**Comment by TommyZihao** [comment]
期待cogvlm2-grounding版本，正在做机械臂相关的demo，太需要了
![架构图4](https://github.com/THUDM/CogVLM2/assets/36354458/5d5d78a8-44c2-4059-9d93-55a67f9f220a)
