### ISSUE TITLE
运行镜像

### ISSUE THREAD

**Issue by zhaoliao2012** [THUDM/CogVLM2#62]
### Feature request  / 功能建议

是否能提供一个finetune使用的dockerfile，默认的安装在测试官方样例会最后会出现一些字符转换问题

### Motivation / 动机

测试微调

### Your contribution / 您的贡献

微调完成后出错

**Comment by zRzRzRzRzRzRzR** [comment]
目前没有呢，
需要在Ubuntu 8卡A100 或者H100部署微调方案，
用UTF-8格式
