### ISSUE TITLE
支持flash attention2吗

### ISSUE THREAD

**Issue by chensongcan** [THUDM/CogVLM2#65]
### System Info / 系統信息

支持flash attention2吗

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

支持flash attention2吗

### Expected behavior / 期待表现

支持flash attention2吗

**Comment by zRzRzRzRzRzRzR** [comment]
已经用了，torch2.2以后都是自带的，不用单独装
模型支持
