### ISSUE TITLE
python cli_demo_multi_gpus.py老是说RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:5 and cuda:0! (when checking argument for argument weight in method wrapper_CUDA__cudnn_convolution)有大佬看解决吗

### ISSUE THREAD

**Issue by NEU-VIOP** [THUDM/CogVLM2#69]
### System Info / 系統信息

python cli_demo_multi_gpus.py老是说RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:5 and cuda:0! (when checking argument for argument weight in method wrapper_CUDA__cudnn_convolution)有大佬看解决吗

### Who can help? / 谁可以帮助到您？

python cli_demo_multi_gpus.py老是说RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:5 and cuda:0! (when checking argument for argument weight in method wrapper_CUDA__cudnn_convolution)有大佬看解决吗

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

python cli_demo_multi_gpus.py老是说RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:5 and cuda:0! (when checking argument for argument weight in method wrapper_CUDA__cudnn_convolution)有大佬看解决吗

### Expected behavior / 期待表现

python cli_demo_multi_gpus.py老是说RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:5 and cuda:0! (when checking argument for argument weight in method wrapper_CUDA__cudnn_convolution)有大佬看解决吗

**Comment by zRzRzRzRzRzRzR** [comment]
两张卡还是多少张卡的部署呢

**Comment by Summer-nan** [comment]
请问一下这个问题是怎么解决的呀？

**Comment by zRzRzRzRzRzRzR** [comment]
如果是两张卡以上，请使用多卡的demo并更新最新的cogvlm2文件，并查看我们的readme中关于多卡推理的限制
