### ISSUE TITLE
上传图片提出问题后报错

### ISSUE THREAD

**Issue by FFFFFFpy** [THUDM/CogVLM2#70]
### System Info / 系統信息

packages in environment at C:\MiniConda3\envs\cogvlm2:
#
# Name                    Version                   Build  Channel
accelerate                0.30.1                   pypi_0    pypi
aiofiles                  23.2.1                   pypi_0    pypi
annotated-types           0.7.0                    pypi_0    pypi
anyio                     3.7.1                    pypi_0    pypi
asyncer                   0.0.2                    pypi_0    pypi
bidict                    0.23.1                   pypi_0    pypi
bitsandbytes              0.43.1                   pypi_0    pypi
bzip2                     1.0.8                h2bbff1b_6
ca-certificates           2024.3.11            haa95532_0
certifi                   2024.2.2                 pypi_0    pypi
chainlit                  1.1.202                  pypi_0    pypi
charset-normalizer        3.3.2                    pypi_0    pypi
chevron                   0.14.0                   pypi_0    pypi
click                     8.1.7                    pypi_0    pypi
colorama                  0.4.6                    pypi_0    pypi
dataclasses-json          0.5.14                   pypi_0    pypi
deprecated                1.2.14                   pypi_0    pypi
distro                    1.9.0                    pypi_0    pypi
einops                    0.8.0                    pypi_0    pypi
exceptiongroup            1.2.1                    pypi_0    pypi
fastapi                   0.110.3                  pypi_0    pypi
fastapi-socketio          0.0.10                   pypi_0    pypi
filelock                  3.14.0                   pypi_0    pypi
filetype                  1.2.0                    pypi_0    pypi
fsspec                    2024.5.0                 pypi_0    pypi
googleapis-common-protos  1.63.0                   pypi_0    pypi
grpcio                    1.64.0                   pypi_0    pypi
h11                       0.14.0                   pypi_0    pypi
httpcore                  1.0.5                    pypi_0    pypi
httpx                     0.27.0                   pypi_0    pypi
huggingface-hub           0.23.2                   pypi_0    pypi
idna                      3.7                      pypi_0    pypi
importlib-metadata        7.0.0                    pypi_0    pypi
intel-openmp              2021.4.0                 pypi_0    pypi
jinja2                    3.1.4                    pypi_0    pypi
lazify                    0.4.0                    pypi_0    pypi
libffi                    3.4.4                hd77b12b_1
literalai                 0.0.601                  pypi_0    pypi
loguru                    0.7.2                    pypi_0    pypi
markupsafe                2.1.5                    pypi_0    pypi
marshmallow               3.21.2                   pypi_0    pypi
mkl                       2021.4.0                 pypi_0    pypi
mpmath                    1.3.0                    pypi_0    pypi
mypy-extensions           1.0.0                    pypi_0    pypi
nest-asyncio              1.6.0                    pypi_0    pypi
networkx                  3.3                      pypi_0    pypi
numpy                     1.26.4                   pypi_0    pypi
openai                    1.30.5                   pypi_0    pypi
openssl                   3.0.13               h2bbff1b_2
opentelemetry-api         1.24.0                   pypi_0    pypi
opentelemetry-exporter-otlp 1.24.0                   pypi_0    pypi
opentelemetry-exporter-otlp-proto-common 1.24.0                   pypi_0    pypi
opentelemetry-exporter-otlp-proto-grpc 1.24.0                   pypi_0    pypi
opentelemetry-exporter-otlp-proto-http 1.24.0                   pypi_0    pypi
opentelemetry-instrumentation 0.45b0                   pypi_0    pypi
opentelemetry-proto       1.24.0                   pypi_0    pypi
opentelemetry-sdk         1.24.0                   pypi_0    pypi
opentelemetry-semantic-conventions 0.45b0                   pypi_0    pypi
packaging                 23.2                     pypi_0    pypi
pillow                    10.3.0                   pypi_0    pypi
pip                       24.0            py310haa95532_0
protobuf                  4.25.3                   pypi_0    pypi
psutil                    5.9.8                    pypi_0    pypi
pydantic                  2.7.2                    pypi_0    pypi
pydantic-core             2.18.3                   pypi_0    pypi
pyjwt                     2.8.0                    pypi_0    pypi
python                    3.10.12              he1021f5_0
python-dotenv             1.0.1                    pypi_0    pypi
python-engineio           4.9.1                    pypi_0    pypi
python-multipart          0.0.9                    pypi_0    pypi
python-socketio           5.11.2                   pypi_0    pypi
pyyaml                    6.0.1                    pypi_0    pypi
regex                     2024.5.15                pypi_0    pypi
requests                  2.32.3                   pypi_0    pypi
safetensors               0.4.3                    pypi_0    pypi
setuptools                69.5.1          py310haa95532_0
simple-websocket          1.0.0                    pypi_0    pypi
sniffio                   1.3.1                    pypi_0    pypi
sqlite                    3.45.3               h2bbff1b_0
sse-starlette             2.1.0                    pypi_0    pypi
starlette                 0.37.2                   pypi_0    pypi
sympy                     1.12.1                   pypi_0    pypi
syncer                    2.0.3                    pypi_0    pypi
tbb                       2021.12.0                pypi_0    pypi
timm                      1.0.3                    pypi_0    pypi
tk                        8.6.14               h0416ee5_0
tokenizers                0.19.1                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
torch                     2.3.0+cu118              pypi_0    pypi
torchvision               0.18.0+cu118             pypi_0    pypi
tqdm                      4.66.4                   pypi_0    pypi
transformers              4.41.1                   pypi_0    pypi
triton                    2.1.0                    pypi_0    pypi
typing-extensions         4.12.0                   pypi_0    pypi
typing-inspect            0.9.0                    pypi_0    pypi
tzdata                    2024a                h04d1e81_0
uptrace                   1.24.0                   pypi_0    pypi
urllib3                   2.2.1                    pypi_0    pypi
uvicorn                   0.25.0                   pypi_0    pypi
vc                        14.2                 h2eaa2aa_1
vs2015_runtime            14.29.30133          h43f2093_3
watchfiles                0.20.0                   pypi_0    pypi
wheel                     0.43.0          py310haa95532_0
win32-setctime            1.1.0                    pypi_0    pypi
wrapt                     1.16.0                   pypi_0    pypi
wsproto                   1.2.0                    pypi_0    pypi
xformers                  0.0.26.post1+cu118          pypi_0    pypi
xz                        5.4.6                h8cc25b3_1
zipp                      3.19.0                   pypi_0    pypi
zlib                      1.2.13               h8cc25b3_1

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x19): undefined reference to `__imp__PyArg_ParseTuple_SizeT'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x69): undefined reference to `__imp__PyArg_ParseTuple_SizeT'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x108): undefined reference to `__imp_PyGILState_Ensure'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x114): undefined reference to `__imp_PyExc_RuntimeError'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x11d): undefined reference to `__imp_PyErr_SetString'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x125): undefined reference to `__imp_PyGILState_Release'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x159): undefined reference to `__imp__PyArg_ParseTuple_SizeT'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x163): undefined reference to `__imp_PyEval_SaveThread'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x17d): undefined reference to `__imp_PyEval_RestoreThread'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x184): undefined reference to `__imp__Py_NoneStruct'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x1b0): undefined reference to `__imp_PyEval_RestoreThread'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x1ea): undefined reference to `__imp__PyArg_ParseTuple_SizeT'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x1fe): undefined reference to `__imp_PyEval_SaveThread'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x21e): undefined reference to `__imp_PyEval_RestoreThread'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x225): undefined reference to `__imp__Py_NoneStruct'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x250): undefined reference to `__imp_PyEval_RestoreThread'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x279): undefined reference to `__imp__PyArg_ParseTuple_SizeT'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x283): undefined reference to `__imp_PyEval_SaveThread'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x2a2): undefined reference to `__imp_PyEval_RestoreThread'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x2ad): undefined reference to `__imp_PyLong_FromUnsignedLongLong'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x2d0): undefined reference to `__imp_PyEval_RestoreThread'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x2f8): undefined reference to `__imp__PyArg_ParseTuple_SizeT'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x405): undefined reference to `__imp__Py_BuildValue_SizeT'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x4ad): undefined reference to `__imp__PyArg_ParseTuple_SizeT'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x4df): undefined reference to `__imp_PyEval_SaveThread'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x5be): undefined reference to `__imp_PyEval_RestoreThread'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x5c4): undefined reference to `__imp_PyErr_Occurred'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x5f4): undefined reference to `__imp__Py_BuildValue_SizeT'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x655): undefined reference to `__imp_PyEval_RestoreThread'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x80a): undefined reference to `__imp_PyList_Type'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x867): undefined reference to `__imp__PyArg_ParseTuple_SizeT'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x882): undefined reference to `__imp_PyList_Size'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x8a6): undefined reference to `__imp_PyList_GetItem'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x8af): undefined reference to `__imp_PyLong_AsUnsignedLongLong'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x8f5): undefined reference to `__imp_PyList_GetItem'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x8ff): undefined reference to `__imp_PyLong_AsUnsignedLongLong'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x94e): undefined reference to `__imp_PyList_GetItem'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x958): undefined reference to `__imp_PyLong_AsUnsignedLong'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x9af): undefined reference to `__imp_PyList_GetItem'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x9b8): undefined reference to `__imp_PyLong_AsUnsignedLong'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x9ef): undefined reference to `__imp_PyEval_SaveThread'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0xa64): undefined reference to `__imp_PyEval_RestoreThread'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0xa92): undefined reference to `__imp_PyLong_FromUnsignedLongLong'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0xac0): undefined reference to `__imp_PyEval_RestoreThread'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0xb13): undefined reference to `__imp_PyExc_RuntimeError'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0xb25): undefined reference to `__imp_PyErr_SetString'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0xb33): undefined reference to `__imp_PyExc_RuntimeError'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0xb45): undefined reference to `__imp_PyErr_SetString'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0xbb9): undefined reference to `__imp__PyArg_ParseTuple_SizeT'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0xbc8): undefined reference to `__imp_PyEval_SaveThread'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0xbf3): undefined reference to `__imp_PyEval_RestoreThread'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0xccd): undefined reference to `__imp_PyLong_FromLong'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0xd53): undefined reference to `__imp_PyGILState_Ensure'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0xd5f): undefined reference to `__imp_PyExc_RuntimeError'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0xd68): undefined reference to `__imp_PyErr_SetString'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0xd70): undefined reference to `__imp_PyGILState_Release'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0xe06): undefined reference to `__imp_PyGILState_Ensure'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0xe12): undefined reference to `__imp_PyExc_RuntimeError'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0xe1b): undefined reference to `__imp_PyErr_SetString'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0xe23): undefined reference to `__imp_PyGILState_Release'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0xe2c): undefined reference to `__imp_PyEval_RestoreThread'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0xe83): undefined reference to `__imp_PyExc_RuntimeError'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0xe95): undefined reference to `__imp_PyErr_SetString'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0xe9e): undefined reference to `__imp_PyExc_RuntimeError'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0xeb0): undefined reference to `__imp_PyErr_SetString'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0xed8): undefined reference to `__imp_PyModule_Create2'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0xeeb): undefined reference to `__imp_PyDict_New'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0xef5): undefined reference to `__imp_PyLong_FromLong'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0xf03): undefined reference to `__imp_PyDict_SetItemString'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x1032): undefined reference to `__imp_PyObject_SetAttrString'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x108f): undefined reference to `__imp_PyObject_SetAttrString'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x1102): undefined reference to `__imp_PyObject_SetAttrString'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x1175): undefined reference to `__imp_PyObject_SetAttrString'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x11bc): undefined reference to `__imp_PyObject_SetAttrString'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x11ca): undefined reference to `__imp_PyType_Ready'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x11e9): undefined reference to `__imp_PyModule_AddObject'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x1232): undefined reference to `__imp_PyModule_AddFunctions'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x1247): undefined reference to `__imp_PyExc_TypeError'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x1257): undefined reference to `__imp_PyErr_SetString'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x1263): undefined reference to `__imp_PyExc_RuntimeError'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x1273): undefined reference to `__imp_PyErr_SetString'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x1283): undefined reference to `__imp_PyExc_TypeError'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x1293): undefined reference to `__imp_PyErr_SetString'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x12a3): undefined reference to `__imp_PyExc_RuntimeError'
C:\Users\PC\AppData\Local\Temp\cckV9X3v.o:main.c:(.text+0x12b3): undefined reference to `__imp_PyErr_SetString'
collect2.exe: error: ld returned 1 exit status
Traceback (most recent call last):
  File "C:\E\CogVLM2\basic_demo\cli_demo.py", line 103, in <module>
    outputs = model.generate(**inputs, **gen_kwargs)
  File "C:\MiniConda3\envs\cogvlm2\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\MiniConda3\envs\cogvlm2\lib\site-packages\transformers\generation\utils.py", line 1758, in generate
    result = self._sample(
  File "C:\MiniConda3\envs\cogvlm2\lib\site-packages\transformers\generation\utils.py", line 2397, in _sample
    outputs = self(
  File "C:\MiniConda3\envs\cogvlm2\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\MiniConda3\envs\cogvlm2\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\MiniConda3\envs\cogvlm2\lib\site-packages\accelerate\hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "C:\Users\PC\.cache\huggingface\modules\transformers_modules\cogvlm2-llama3-chat-19B-int4\modeling_cogvlm.py", line 620, in forward
    outputs = self.model(
  File "C:\MiniConda3\envs\cogvlm2\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\MiniConda3\envs\cogvlm2\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\MiniConda3\envs\cogvlm2\lib\site-packages\accelerate\hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "C:\Users\PC\.cache\huggingface\modules\transformers_modules\cogvlm2-llama3-chat-19B-int4\modeling_cogvlm.py", line 402, in forward
    return self.llm_forward(
  File "C:\Users\PC\.cache\huggingface\modules\transformers_modules\cogvlm2-llama3-chat-19B-int4\modeling_cogvlm.py", line 486, in llm_forward
    layer_outputs = decoder_layer(
  File "C:\MiniConda3\envs\cogvlm2\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\MiniConda3\envs\cogvlm2\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\MiniConda3\envs\cogvlm2\lib\site-packages\accelerate\hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "C:\Users\PC\.cache\huggingface\modules\transformers_modules\cogvlm2-llama3-chat-19B-int4\modeling_cogvlm.py", line 261, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "C:\MiniConda3\envs\cogvlm2\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\MiniConda3\envs\cogvlm2\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\MiniConda3\envs\cogvlm2\lib\site-packages\accelerate\hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "C:\Users\PC\.cache\huggingface\modules\transformers_modules\cogvlm2-llama3-chat-19B-int4\modeling_cogvlm.py", line 204, in forward
    query_states, key_states = self.rotary_emb(query_states, key_states, position_ids=position_ids, max_seqlen=position_ids.max() + 1)
  File "C:\MiniConda3\envs\cogvlm2\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\MiniConda3\envs\cogvlm2\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\MiniConda3\envs\cogvlm2\lib\site-packages\accelerate\hooks.py", line 166, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "C:\Users\PC\.cache\huggingface\modules\transformers_modules\cogvlm2-llama3-chat-19B-int4\util.py", line 469, in forward
    q = apply_rotary_emb_func(
  File "C:\Users\PC\.cache\huggingface\modules\transformers_modules\cogvlm2-llama3-chat-19B-int4\util.py", line 329, in apply_rotary_emb
    return ApplyRotaryEmb.apply(
  File "C:\MiniConda3\envs\cogvlm2\lib\site-packages\torch\autograd\function.py", line 598, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "C:\Users\PC\.cache\huggingface\modules\transformers_modules\cogvlm2-llama3-chat-19B-int4\util.py", line 255, in forward
    out = apply_rotary(
  File "C:\Users\PC\.cache\huggingface\modules\transformers_modules\cogvlm2-llama3-chat-19B-int4\util.py", line 212, in apply_rotary
    rotary_kernel[grid](
  File "C:\MiniConda3\envs\cogvlm2\lib\site-packages\triton\runtime\jit.py", line 166, in <lambda>
    return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
  File "C:\MiniConda3\envs\cogvlm2\lib\site-packages\triton\runtime\jit.py", line 348, in run
    device = driver.get_current_device()
  File "C:\MiniConda3\envs\cogvlm2\lib\site-packages\triton\runtime\driver.py", line 230, in __getattr__
    self._initialize_obj()
  File "C:\MiniConda3\envs\cogvlm2\lib\site-packages\triton\runtime\driver.py", line 227, in _initialize_obj
    self._obj = self._init_fn()
  File "C:\MiniConda3\envs\cogvlm2\lib\site-packages\triton\runtime\driver.py", line 260, in initialize_driver
  File "C:\MiniConda3\envs\cogvlm2\lib\site-packages\triton\runtime\driver.py", line 122, in __init__
    self.utils = CudaUtils()
  File "C:\MiniConda3\envs\cogvlm2\lib\site-packages\triton\runtime\driver.py", line 69, in __init__
    so = _build("cuda_utils", src_path, tmpdir)
  File "C:\MiniConda3\envs\cogvlm2\lib\site-packages\triton\common\build.py", line 124, in _build
    ret = subprocess.check_call(cc_cmd)
  File "C:\MiniConda3\envs\cogvlm2\lib\subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\E\\mingw64\\bin\\gcc.EXE', 'C:\\Users\\PC\\AppData\\Local\\Temp\\tmpbdvus3wu\\main.c', '-O3', '-shared', '-IC:\\MiniConda3\\envs\\cogvlm2\\lib\\site-packages\\triton\\common\\..\\third_party\\cuda\\include', '-IC:\\MiniConda3\\envs\\cogvlm2\\Include', '-IC:\\Users\\PC\\AppData\\Local\\Temp\\tmpbdvus3wu', '-LC:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.8\\lib\\x64', '-LC:\\MiniConda3\\envs\\cogvlm2\\libs', '-lcuda', '-o', 'C:\\Users\\PC\\AppData\\Local\\Temp\\tmpbdvus3wu\\cuda_utils.cp310-win_amd64.pyd']' returned 
non-zero exit status 1.

### Expected behavior / 期待表现

正常运行

**Comment by zRzRzRzRzRzRzR** [comment]
windows系统跑不了吧，会有依赖错误 强行便衣可能导致cuda方面适配问题吧
