### ISSUE TITLE
Error after finishing first epoch with latest code

### ISSUE THREAD

**Issue by hvico** [THUDM/CogVLM2#72]
### System Info / 系統信息

Using requirements.txt from sample code.

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

Reproduced finetuning example with latest code.

Got this error right after it finished the first epoch and it starts to do the eval:

Epoch 0: Average Loss 1.3389, Perplexity 3.8147
  0%|                                                                                                                                                                                     | 0/5668 [00:00<?, ?it/s]
[rank0]: Traceback (most recent call last):
[rank0]:   File "/root/CogVLM2/finetune_demo/peft_lora.py", line 346, in <module>
[rank0]:     main()
[rank0]:   File "/root/CogVLM2/finetune_demo/peft_lora.py", line 321, in main
[rank0]:     outputs = accelerator.unwrap_model(model)(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/peft/peft_model.py", line 1430, in forward
[rank0]:     return self.base_model(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/peft/tuners/tuners_utils.py", line 179, in forward
[rank0]:     return self.model.forward(*args, **kwargs)
[rank0]: TypeError: CogVLMForCausalLM.forward() got an unexpected keyword argument 'is_ds_zero_3'
[2024-05-31 03:00:34,263] [INFO] [launch.py:319:sigkill_handler] Killing subprocess 3632
[2024-05-31 03:00:34,264] [ERROR] [launch.py:325:sigkill_handler] ['/usr/bin/python3', '-u', 'peft_lora.py', '--local_rank=0', '--ds_config', 'ds_config.yaml'] exits with return code = 1

That didn't happen with the first version of the finetuning script I tried. I didn't apply any changes to DS configuration, no DS3 setup, just the one bundled with the project.

### Expected behavior / 期待表现

Eval works, next epoch starts.

**Comment by zRzRzRzRzRzRzR** [comment]
is_ds_zero_3 这个部分我之后移掉，目前不支持
