### ISSUE TITLE
为 Demo 增加 Repetition Penalty 参数设置

### ISSUE THREAD

**Issue by shayeboshi** [THUDM/CogVLM2#74]
### Feature request  / 功能建议

增加一个重复性惩罚参数来控制模型生成的结果

### Motivation / 动机

在 Demo 试用时某些图片能稳定复现比较极端的重复，正常生成到中途开始自我重复直到 max_new_tokens

### Your contribution / 您的贡献

None

**Comment by zRzRzRzRzRzRzR** [comment]
这个功能很好加，在生产环境的话你用openai api格式传入就能带这个参数了
