### ISSUE TITLE
【question】 您好，如果将pdf转换成图片应该怎么让模型同时阅读多种图片并回答问题

### ISSUE THREAD

**Issue by whysirier** [THUDM/CogVLM2#76]
### System Info / 系統信息

pdf结合langchain可能效果差点，但直接阅读图片，效果不错。demo中每次只能提交一张图片和一个question，请问怎么提交多张图片和一个question这种形式。

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

V100 32GB * 2

### Expected behavior / 期待表现

期待回答

**Comment by whysirier** [comment]
是多张图片，说错了

**Comment by whysirier** [comment]
感觉这个单图识别很强啊，比Qwen强了不少，用得也很方便

**Comment by zRzRzRzRzRzRzR** [comment]
可以查看 #84 #83 ，不支持多个图片
