### ISSUE TITLE
int4的模型精度很低，正常吗

### ISSUE THREAD

**Issue by cuppersd** [THUDM/CogVLM2#77]
### Feature request  / 功能建议

int4的模型精度很低，正常吗

### Motivation / 动机

int4的模型精度很低，正常吗

### Your contribution / 您的贡献

int4的模型精度很低，正常吗

**Comment by zRzRzRzRzRzRzR** [comment]
我们的测试都是在BF16上测试的，INT4是直接用bnb量化的，效果有一定下降
