### ISSUE TITLE
目前openai_api方式中不支持role:system，导致很难对assistant做一些设定，请考虑添加role:system

### ISSUE THREAD

**Issue by hankewei** [THUDM/CogVLM2#79]
### Feature request  / 功能建议

目前openai_api方式中不支持role:system，导致很难对assistant做一些设定，请考虑添加role:system

### Motivation / 动机

目前openai_api方式中不支持role:system，导致很难对assistant做一些设定，请考虑添加role:system

### Your contribution / 您的贡献

无

**Comment by wfnian** [comment]
同问，如何增加系统提示词？

**Comment by zRzRzRzRzRzRzR** [comment]
模型本身是没有sys的，所以传入sys也是没用的吧？
