### ISSUE TITLE
basic_demofastapi>=0.111.0 because these package versions have conflicting dependencies.

### ISSUE THREAD

**Issue by menkeyi001** [THUDM/CogVLM2#8]
### System Info / 系統信息

ubuntu22.04

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

(CogVLM2_basic_demo) root@com2:~/CogVLM2-main/basic_demo# pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
Collecting chainlit>=1.0.506 (from -r requirements.txt (line 7))
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/1b/5c/2e334ba1de3170354232bce9f0344594cfbececc6f992da8412f64d484f5/chainlit-1.1.0-py3-none-any.whl (4.4 MB)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/3d/7c/5c94714d7b277f55048df8433c9cd0be3eed7eed82ca89a629d1b3b59c02/chainlit-1.0.506-py3-none-any.whl (4.4 MB)
ERROR: Cannot install -r requirements.txt (line 7) and fastapi>=0.111.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested fastapi>=0.111.0
    chainlit 1.1.101 depends on fastapi<0.111.0 and >=0.110.1
    The user requested fastapi>=0.111.0
    chainlit 1.1.0 depends on fastapi<0.111.0 and >=0.110.1
    The user requested fastapi>=0.111.0
    chainlit 1.0.506 depends on fastapi<0.111.0 and >=0.110.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

### Expected behavior / 期待表现

应该用什么版本

**Comment by zRzRzRzRzRzRzR** [comment]
chainlit 1.0.506 为准，fastapi可以调整到0.110.1
