### ISSUE TITLE
您好，目前不支持多图片问答，请问什么时候开放该功能

### ISSUE THREAD

**Issue by whysirier** [THUDM/CogVLM2#81]
### System Info / 系統信息

![企业微信截图_20240605094155](https://github.com/THUDM/CogVLM2/assets/142364107/b7816b21-05db-4d01-8248-da0f6253dcb7)

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

if image_path == '':
            image_lst = None
        else:
            image_lst = []
            file_paths = []
            for root, directories, files in os.walk(image_path):
                for file in files:
                    file_paths.append(os.path.join(root, file))
            for file_path in file_paths:
                image_lst.append(Image.open(file_path).convert('RGB'))
                print(file_path)

        if image_lst is None:
            input_by_model = self.model.build_conversation_input_ids(self.tokenizer,
                    query = query,
                    history=history,
                    template_version='chat'
                    )
        else:
            input_by_model = self.model.build_conversation_input_ids(self.tokenizer,
                    query = query,
                    history=history,
                    images=image_lst,
                    template_version='chat'
                    )
        inputs = {
                'input_ids': input_by_model['input_ids'].unsqueeze(0).to(self.DEVICE),
                'token_type_ids': input_by_model['token_type_ids'].unsqueeze(0).to(self.DEVICE),
                'attention_mask': input_by_model['attention_mask'].unsqueeze(0).to(self.DEVICE),
                'images': [[input_by_model['images'][0].to(self.DEVICE).to(self.TORCH_TYPE)]] if image_lst is not None else None,
                }

### Expected behavior / 期待表现

期待回复

**Comment by zRzRzRzRzRzRzR** [comment]
模型的结构上只能对单个图片进行对话和提问哦
