### ISSUE TITLE
CogVLM如何才能做图像中对象的定位任务呢？

### ISSUE THREAD

**Issue by tiandazhao** [THUDM/CogVLM2#82]
### System Info / 系統信息

大家好，cogvlm2可以做对象标注任务吗？尝试过很多类型的prompt，都不能顺利输出图片的坐标，想问下，官方做在训练该类型任务时，有没有推荐的prompt啊

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

<img width="780" alt="image" src="https://github.com/THUDM/CogVLM2/assets/38110029/dad5e08f-bf00-41a5-8309-a6d4996d7617">

### Expected behavior / 期待表现

期待能标出图片的中制定对象的坐标

**Comment by zRzRzRzRzRzRzR** [comment]
see #84
