### ISSUE TITLE
CogVLM2如何完成图像目标检测或者分割任务？

### ISSUE THREAD

**Issue by FanZhang91** [THUDM/CogVLM2#84]
### System Info / 系統信息

我想用CogVLM2模型进行图像目标检测任务。运行cli_demo.py脚本后，无论我输入什么图像数据模型输出的都是promt中包含示例的结果(对象左上角和右下角坐标)。请问能给出关于目标检测/分割任务具体的prompt信息吗？

### Who can help? / 谁可以帮助到您？

无

### Information / 问题信息

- [ ] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

无

### Expected behavior / 期待表现

无

**Comment by zRzRzRzRzRzRzR** [comment]
cogvlm2暂时未提供目标检测和语义分割的版本。
cogvlm前一代作品有grounding模型根据用户输入回复bbx，但是也不能返回像素级的分割

**Comment by FanZhang91** [comment]
好的，感谢您的回复。
















在 2024-06-07 09:40:03，"zR" ***@***.***> 写道：

cogvlm2暂时未提供目标检测和语义分割的版本。
cogvlm前一代作品有grounding模型根据用户输入回复bbx，但是也不能返回像素级的分割
