### ISSUE TITLE
提供 cogvlm2-llama3-chat-19B-Int4 的微调代码

### ISSUE THREAD

**Issue by aqingcv** [THUDM/CogVLM2#87]
### Feature request  / 功能建议

请问能提供 huggingface 版本模型 cogvlm2-llama3-chat-19B-Int4 的微调代码吗

### Motivation / 动机

无

### Your contribution / 您的贡献

无

**Comment by zRzRzRzRzRzRzR** [comment]
理论可以，但是实际性能表现不佳。推荐使用BF16进行微调
目前，我们没有提供hf上 int4微调的办法的相关计划。
感谢您的支持
