### ISSUE TITLE
openai_api_demo.py失败

### ISSUE THREAD

**Issue by xiaoToby** [THUDM/CogVLM2#92]
### System Info / 系統信息

python:3.10
torch: 2.2.2

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [ ] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

![image](https://github.com/THUDM/CogVLM2/assets/40045458/ca6aa999-96f3-4ad0-ace0-9bb94255e062)
![image](https://github.com/THUDM/CogVLM2/assets/40045458/5d3800b1-ba0f-4823-9208-431556211c64)

### Expected behavior / 期待表现

name=None?

**Comment by xiaoToby** [comment]
python openai_api_request.py 也是报同样的错
是因为哪个依赖的版本原因吗

**Comment by xiaoToby** [comment]
@zRzRzRzRzRzRzR

**Comment by zRzRzRzRzRzRzR** [comment]
为什么会在这个仓库提问chatglm，这个仓库的demo和chatglm不兼容的呀

**Comment by xiaoToby** [comment]
> 为什么会在这个仓库提问chatglm，这个仓库的demo和chatglm不兼容的呀

不是啊，我是用的你们2024/6/5更新的glm-4v-9B这个模型，用的是你们的basic_demo里的openai_api_demo.py和openai_api_request.py

**Comment by xiaoToby** [comment]
我只是在基于openai_api_demo.py上做了一个鉴权，为了辨识所以文件名改成了openai_api_glm_4v_9b.py

**Comment by xzm123456** [comment]
请问哥们你的访问这个接口的方式是什么？postman还是直接python文件，能给个实例参考下吗？我访问的接口智能成功一个
。。。

**Comment by xiaoToby** [comment]
> 请问哥们你的访问这个接口的方式是什么？postman还是直接python文件，能给个实例参考下吗？我访问的接口智能成功一个 。。。

就是用的basic_demo里的openai的两个python文件

**Comment by xiaoToby** [comment]
> 为什么会在这个仓库提问chatglm，这个仓库的demo和chatglm不兼容的呀

确实，basic_demo里的openai支持的是cogvlm2，对glm-4v-9B不支持

**Comment by xzm123456** [comment]
> > 请问哥们你的访问这个接口的方式是什么？postman还是直接python文件，能给个实例参考下吗？我访问的接口智能成功一个 。。。
> 
> 就是用的basic_demo里的openai的两个python文件

能给我看一下你访问的界面吗？postman还是python的requests方式

**Comment by xiaoToby** [comment]
> ython的requests方式

直接就是在终端先python openai_api_demo.py,然后再 python openai_api_request.py
basic_demo目录里有案例图片的，所以都不需要用postman

**Comment by xzm123456** [comment]
> > ython的requests方式
> 
> 直接就是在终端先python openai_api_demo.py,然后再 python openai_api_request.py basic_demo目录里有案例图片的，所以都不需要用postman

卧槽，我只执行了第一个。。。。，

**Comment by xzm123456** [comment]
哥们，请教一下，你是用docker镜像启动的吗？有没有dockerfile可以参考一下，我这个就报错。。。

**Comment by xiaoToby** [comment]
是在容器内启的服务，把模型文件和依赖下载好就行了

**Comment by xiaoToby** [comment]
![image](https://github.com/THUDM/CogVLM2/assets/40045458/1f4954f2-f091-4bf2-98fd-3793d937e856)

还有一个问题，就是和cogvlm2-llama3-chinese-chat-19B模型进行对话，如果没有图片输入，只有文字，就会报上图中的错误。
因为我是第一次使用多模态模型，是不是必须要有图片的输入？
@zRzRzRzRzRzRzR

**Comment by zRzRzRzRzRzRzR** [comment]
这个模型最好要有图像输入，才能稳定的运行，我在这个demo确实设定了一定要有图像输入
