### ISSUE TITLE
memory_efficient_attention to flash_attn

### ISSUE THREAD

**Issue by lk137095576** [THUDM/CogVLM2#95]
### Feature request  / 功能建议

visual中默认用的是 xformers：
out = xops.memory_efficient_attention(q, k, v, scale=self.scale,)

是否可以修改可以选，增加args可选flash attention

### Motivation / 动机

flash attention灵活一些

### Your contribution / 您的贡献

https://github.com/Dao-AILab/flash-attention/blob/main/flash_attn/flash_attn_interface.py#L1085

**Comment by zRzRzRzRzRzRzR** [comment]
这个地方改不了，一定需要使用xformers的这个组件才能保证效果较好
