### ISSUE TITLE
新增accumulate, packing &  关于padding

### ISSUE THREAD

**Issue by lk137095576** [THUDM/CogVLM2#98]
### Feature request  / 功能建议

lora 两个问题：
1. 新增accumulata
2. self.padding_len = 2303    为什么是2303？很奇怪的数字

### Motivation / 动机

none

### Your contribution / 您的贡献

none

**Comment by zRzRzRzRzRzRzR** [comment]
2303 这个是图像padding的长度，一定要加

**Comment by lk137095576** [comment]
> 2303 这个是图像padding的长度，一定要加

我在微信群里问了，但是还没回我，我这里再写一下
我看了下图片占用，（2306, 4096），其中2304是768*3，加上boi和eoi（全0）一共2306 。如果用VISION_TOKEN_TYPE=1作为image的flag，即使是2304的图片部分也放不下
而且我试了试，2306和2303都可以填充。感觉是index_put这个不需要完全匹配也可以填充。
inputs_embeds = inputs_embeds.index_put([token_type_ids == VISION_TOKEN_TYPE], images_features)

**Comment by lk137095576** [comment]
无论是2303还是2306都对性能不友好，为什么不用2408这种尺寸？
