### ISSUE TITLE
您好，CoGVLM2无法读取多张图片，请问有什么方法能够解决该问题，

### ISSUE THREAD

**Issue by whysirier** [THUDM/CogVLM2#99]
### System Info / 系統信息

只能通过多轮对话结合历史回答来解决？

### Information / 问题信息

- [X] The official example scripts / 官方的示例脚本
- [X] My own modified scripts / 我自己修改的脚本和任务

### Reproduction / 复现过程

不是bug

### Expected behavior / 期待表现

期待回答

**Comment by zRzRzRzRzRzRzR** [comment]
模型结构导致模型只能传入一张图片，能做的只能把多个图片拼成一个图片传入。

**Comment by whysirier** [comment]
> 模型结构导致模型只能传入一张图片，能做的只能把多个图片拼成一个图片传入。

会不会超过token限制，传入image会有分辨率限制吧？我是一张张的将内容识别出来，再合并

**Comment by zRzRzRzRzRzRzR** [comment]
传入image是1344*1344，一个完整对话只能传入一张，这个图像占用的token固定为2303
